# fly.toml app configuration file generated for mydocsbackend on 2024-08-03T11:06:24+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mydocsbackend'
primary_region = 'ams'

[build]

[env]
PORT = '8080'

[deploy]
release_command = "bun run migrate"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
